### ISSUE TITLE
API docs: missing state attributes

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-text-field#102]
Attributes such as `focused`, `focus-ring`, `disabled`, `invalid` are available on the host element for styling, but not listed in the API docs as of now.

API documentation should list all of the attributes available for styling.

**Comment by tomivirkki** [comment]
Fixed in https://github.com/vaadin/vaadin-text-field/commit/beb3f404119af398b539f766640e6ef6c5db517c
