### ISSUE TITLE
[password-field] Mask the password on blur

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#116]
When the user blurs `<vaadin-password-field>` the input should be masked again, to avoid leaving the password visible accidentally.

For this to work nicely, the field needs to be focused when the reveal button is pressed, like it currently is, but that could change in a future update/fix to vaadin-text-field. So it could make sense to add a test for it.

Can anyone think of a use case where this would be a poor default? And if yes, should this behavior be configurable?

**Comment by limonte** [comment]
@jouni question by Leif: should the password-field remember that password was hidden automatically by blur and show the password again after re-focusing?

**Comment by jouni** [comment]
Thanks for asking. I think not. Did this cause some issues in user testing?

**Comment by limonte** [comment]
> Did this cause some issues in user testing?

No, just a question. Let's leave it as it is for now. Thanks!

**Comment by jouni** [comment]
Seems like there’s been a regression with this at some point. The field is no longer focused when clicking the reveal button, so it’s possible to leave the field unmasked accidentally.

Reproducible at https://cdn.vaadin.com/vaadin-text-field/1.2.0-alpha2/demo/#text-field-password-demos

Correct behavior visible at https://cdn.vaadin.com/vaadin-text-field/1.1.0-beta1/demo/#text-field-password-demos

The behavior is still correct in 1.1.0-beta1, but not in 1.1.0 final.
