### ISSUE TITLE
Do not validate vaadin-text-field (and vaadin-password-field) when no pattern and required attributes are present.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/vaadin-text-field#130]
I would like to be able to set the `invalid` status manually, for instance, this way:

`<vaadin-text-field id="textField" value={{text}}></vaadin-text-field>`

```js
// Omitted most of the file for clarity

static get properties() {
    return {
        text: {
            type: String,
            observer: '_textChangeObserver'
        }
    }
}

_textChangeObserver(newValue, oldValue) {
    if (newValue && newValue.startsWith('2')) {
        this.$.textField.invalid = true;
        this.$.textField.errorMessage = "Input should not start with 2";
    } else {
        this.$.textField.invalid = false;
        this.$.textField.errorMessage = "";
    }
}
```

but this is not possible, since every time the component looses focus, it revalidates itself.

Since there were no attributes on the component that may change the validation result, I would have expected the component not to carry out any validation at all.

Can you please fix this?

**Comment by jouni** [comment]
Required flag should be checked still, right? I mean, if a user focuses a required field and then leaves without typing anything, the field should be marked invalid. No need to define a pattern in all cases.

**Comment by SomeoneToIgnore** [comment]
Sure.
Main idea of the ticket is that you cannot validate everything with just `required` and `pattern`: we would like to be able to manage `invalid` and `errorMessage` properties ourselves and be 100% sure that it won't change if there is no `required` and `pattern` fields set (now it does change which is an issue to us)

**Comment by jouni** [comment]
Yeah, I understand the need.

I had a prototype idea a long time ago about making it configurable how validation status is indicated to the user. 

Here’s the gist of it, I guess, https://github.com/vaadin/vaadin-text-field/blob/5690eced3c247b09de821c4017679fd42cd3f755/demo/validation-feedback.html#L32-L99

And the relevant changes for vaadin-text-field: https://github.com/vaadin/vaadin-text-field/commit/5690eced3c247b09de821c4017679fd42cd3f755#diff-fc45d09e1dde251e9b6395613968686b

Here’s the branch for the proto: https://github.com/vaadin/vaadin-text-field/tree/proto/validation-feedback

And the related issue: #16 

Not sure if that would solve your problem, that think it might, that you could just set:
```javascript
textField.indicateInvalidOn = '';
textField.indicateValidOn = '';
```
