### ISSUE TITLE
Rename the dom-module id for vaadin-password-field

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-text-field#140]
I can't see any reason that `<dom-module id="vaadin-password-field-template">` shouldn't be the more logical `<dom-module id="vaadin-password-field">`. Keeping the `id` in sync with the module name and `is()` method is what occurs in the other Vaadin elements I looked at. Having them different can also mess with code completion in IDEs like the JetBrains suite which use the `id`.

**Comment by jouni** [comment]
I assume it’s because password field is extending the template of text field, and its own template contains only the extra pieces that are added to the text field’s template.

I quickly tested this out (removed the `-template` suffix), and that broke at least on Safari.

**Comment by tomivirkki** [comment]
That's correct. Here's where the element picks the pieces from the template https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-password-field.html#L117

**Comment by limonte** [comment]
> That's correct. Here's where the element picks the pieces from the template https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-password-field.html#L117

In [the docs](https://www.polymer-project.org/2.0/docs/devguide/dom-template#inherited-templates) there's no `+ '-template'` part. 

This is a restriction that AFAIK comes from the combination of `themable-mixin` https://github.com/vaadin/vaadin-themable-mixin/blob/master/vaadin-themable-mixin.html#L10-L30 and template inheritance. Didn't have time to investigate that more detaily.

**Comment by jouni** [comment]
From the Polymer docs:
> If the element doesn't provide its own DOM template (using either a <dom-module> or a string template), Polymer uses the same template as the superclass, if any.

So if password field has its own template (named according to Polymer conventions), super.template will return that instead of the template for text field, if I understood correctly.

**Comment by tomivirkki** [comment]
@jouni Yes, that's why it must have some other name like `-template`.

@limonte The example you linked creates the content programmatically. We have more content so we use a template.

**Comment by limonte** [comment]
Oh, I see. Thanks for the clarification @tomivirkki @jouni :+1:

**Comment by moderndeveloperllc** [comment]
@jouni Thanks for the information. I didn't look hard enough at the templating logic. Just thought it might be a mis-name from an earlier alpha or something.
