### ISSUE TITLE
Support `autocapitalize` attribute

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#150]
https://developers.google.com/web/updates/2015/04/autocapitalize

**Comment by heruan** [comment]
Yes, please! Safari always capitalizes my username in `vaadin-text-field` 😄

**Comment by heruan** [comment]
Both `autocorrect` and `autocapitalize` can be useful also in `vaadin-text-area`. Should these be moved/added to the mixin?

**Comment by jouni** [comment]
I think these should apply to all of the text field elements, including password and text area (and the number field once we get to that).
