### ISSUE TITLE
<vaadin-text-area> UX/DX tests

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#154]

**Comment by Toshegg** [comment]
Bug repropduces:

- While selecting buttons in radio-group value demo
- With paper-radio-group instead of vaadin-radio-group
- When placing element outside vaadin-demo-snippet
- When there is only vaadin-button inside demo-snippet

Most probably demo issue.

**Comment by limonte** [comment]
The last comment seems unrelated to this issue.

**Comment by Toshegg** [comment]
https://gitlab.vaadin.com/elements/dx-tests/merge_requests/4

**Comment by Toshegg** [comment]
https://docs.google.com/a/vaadin.com/document/d/1Ml8qxymQ0DU-RBtXLaB8tZR6Oc-zXlyFKDDMD-XXQqM/edit?usp=sharing
