### ISSUE TITLE
Add `autocomplete` support

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-text-field#156]
What is autocomplete: https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/

Live demo: https://jsfiddle.net/6r5htd05/68/

In the live demo above I am able to trigger autocomplete on the native input, but not on the `vaadin-text-field`:

![](https://i.imgur.com/JOQmXan.png)

Chrome/Linux

**Comment by jouni** [comment]
If it’s possible, we should consider adding a new stylable state based on this. So, when the user does choose one of the autofill options, we should add a new attribute on the host element (like `autofilled` or something).

**Comment by limonte** [comment]
This is actually the Shadow DOM limitation: https://jsfiddle.net/Lkw59r2j/

We can't do anything about it :/

**Comment by limonte** [comment]
Related issues:
- https://bugs.chromium.org/p/chromium/issues/detail?id=746593
- https://bugs.webkit.org/show_bug.cgi?id=172567
