### ISSUE TITLE
Autocompleted fields look quite bad

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-text-field#167]
Autocompleted `vaadin-text-field` and `vaadin-password-field` looks quite bad as the browser gives the fields a yellow background to indicate autocomplete, but the theme of textfields do not take this into account. There is white/gray left on both ends.

![screen shot 2017-11-14 at 16 11 38](https://user-images.githubusercontent.com/525503/32784172-bea22386-c956-11e7-81d7-26a0409fcafa.png)

@tomivirkki IMO almost blocking V10.

**Comment by tomivirkki** [comment]
Closing as duplicate to https://github.com/vaadin/vaadin-valo-theme/issues/26
