### ISSUE TITLE
Unpredicted behaviour with whitespaces in the end of the line.

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-text-field#169]
When coming to the end of the line and entering only whitespaces, the cursor is not moving to the new line, however the spaces are still entered to the `text-area`. The same behaviour is present in native `text-area`, but is still confusing for users.

In some cases such behaviour in combination with copy/pasting and entering text causing horizontal scrolling in `text-area` .

**Should we do something with it?**

![spaces_more](https://user-images.githubusercontent.com/29372419/33020991-fe5e8396-ce08-11e7-8b73-6ee952982cf5.gif)

**Comment by jouni** [comment]
Not sure if we can control this somehow. Browsers probably just collapse the whitespace at the end of the line.

**Comment by jouni** [comment]
Closing this as an edge case which we probably can’t fix.
