### ISSUE TITLE
2.0.0alpha-1 - Firefox 57 shows error-message all the time

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-text-field#175]
I would put up a jsbin of this issue, but FF 57 seems to not ant to ply well with polygit. The issue is that when there is an `error-message`, it's being displayed on page load. This is not happening on Safari or Chrome. Something as simple as 
```
<vaadin-text-field id="phone" name="phone" label="Phone Number" pattern="[0-9\-\.]{10,12}" error-message="A valid 10-digit phone number is required" required></vaadin-text-field>
```
should show the problem.

Edit: Just in case you can get it going on FF to see the issue: https://jsbin.com/bezikow/4/edit?html,output

**Comment by jouni** [comment]
Wrap the script with `document.addEventListener('WebComponentsReady', function() {…});` and it should work. Worked for me at least.

Didn’t see the issue, though. Anything special I need to do, or it should just happen on first render?

**Comment by tomivirkki** [comment]
Cannot reproduce. Please re-open is still valid.

**Comment by moderndeveloperllc** [comment]
Either FF fixed it in one of the small patches, or y'all did in the latest alphas. Not seeing the issue now. Thanks.
