### ISSUE TITLE
Alignment issues with new Valo

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#178]
Some regressions with the new theme (vaadin-core-elements-ux app):

- There's a gap after the second form row
- The dropdown indicator is misplaced when a value is selected
- Reveal icon isn't visible in password field
![screenshot 2017-12-18 16 24 05](https://user-images.githubusercontent.com/1222264/34110696-203c9d64-e410-11e7-811b-6d219a986f1f.png)

- With narrow viewport, the text field family elements are sized differently
![screenshot 2017-12-18 16 24 27](https://user-images.githubusercontent.com/1222264/34110695-1d6f7f48-e410-11e7-9e78-b6d9e183ed11.png)

**Comment by jouni** [comment]
Without any debugging:

> There's a gap after the second form row

No idea why that is.

> The dropdown indicator is misplaced when a value is selected

The text-field was updated in isolation, going to revisit dropdown-menu later to fix this

> Reveal icon isn't visible in password field

The new theme depends on some updates in the Valo theme repo (font icon properties). Will be fixed once we have a new version of Valo.

> With narrow viewport, the text field family elements are sized differently

The text-field has a default min-width on the `value` part, so any element with a prefix/suffix will have a larger min-width. Related to the first issue, and will be fixed once dropdown-menu and combo-box themes are updated.

**Comment by jouni** [comment]
Btw, I don’t have access to the vaadin-core-elements-ux app.
