### ISSUE TITLE
Make reveal button accessible with keyboard

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-text-field#191]
Currently there is no way to get to the reveal button with keyboard navigation. Should we change this behaviour or mention a workaround with binding the value of the reveal button (with hiding it) to an external checkbox?

**Comment by Haprog** [comment]
I don't get it. @yuriy-fix should this issue be in some other repository (e.g. vaadin-combo-box)?

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-web-components/issues/120 which describes the same problem.
