### ISSUE TITLE
"invalid" property value change fires event for "value" property.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-text-field#192]
The original report is: https://github.com/vaadin/flow/issues/2460

The issue is:
if "invalid" property value is changed then there will be two events fires: value change event for "invalid" which makes sense and value change event for "value" which has no sense since there were no changes for "value" property.

This inconsistence makes an issue for Flow engine.

**Comment by tomivirkki** [comment]
According to the ticket description, the following should fail:
```
it('should not fire value-changed event', function() {
  const spy = sinon.spy();
  tf.addEventListener('value-changed', spy);
  tf.invalid = true;
  expect(spy.called).to.be.false;
});
```

but it passes fine on master.

**Comment by denis-anisimov** [comment]
Oh, crap.
You are right.
It's our fault. Not client side element.
Sorry :(
