### ISSUE TITLE
disabled text field placeholder text is not shown

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-text-field#198]
How to keep the placeholder text in disabled vaadin-text-field?

**Comment by web-padawan** [comment]
@sudipta1411 you can achieve this by creating theme module and overriding corresponding styles like this:
https://jsbin.com/taqinot/edit?html,output

Read more about theme modules in the [ThemableMixin wiki](https://github.com/vaadin/vaadin-themable-mixin/wiki), hope that helps.

I'm closing this as a non-issue. In the future please ask questions like this in our [Slack channel](https://polymer.slack.com/messages/C6ULJ2F7S)
