### ISSUE TITLE
Safari 10.0 doesn’t support `minlength` validation

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#20]
We should probably not expose the native `minlength` property, as Safari 10.0 doesn’t natively produce validation errors for that. We should instead encourage users to use `pattern` instead.

This has been fixed already in Safari Technology Preview.

Related: `maxlength` works in Safari 10.0 also, it prevents the user from inputting more characters.

Also, it seems that `minlength` and `maxlength` are only evaluated for user input, and they don’t affect the validation unless the user has touched modified the input. The `pattern` property, on the other hand, is validated already when the element is loaded/rendered.

**Comment by tomivirkki** [comment]
Looks like it's fixed in 10.3, closing.
