### ISSUE TITLE
Enable setting type of input field

### ISSUE THREAD

**Issue by caalador** [vaadin/vaadin-text-field#204]
Right now it's not possible to create a email type vaadin-text-field without some javascript
to find the field and then executing `foundFieldElement.shadowRoot.querySelector('input').type = 'email'`.

One could expect that having `<vaadin-text-field type='email'></vaadin-text-field>` would result in the input field being of type `email`

**Comment by web-padawan** [comment]
I remember discussing this with the team, and we had some doubt because of the fact that exposing the `type` attribute itself is not enough without any actual validation, and therefore it might break some users expectations.

**Comment by jouni** [comment]
Thanks for the suggestion.

We’ve so far postponed adding this, as we haven’t come to an agreement/conclusion how the `type` attribute compares to the specialized fields that we have, such as `<vaadin-password-field>`, (upcoming) `<vaadin-number-field>`, and `<vaadin-date-picker>` (which can be considered a replacement for `<vaadin-text-field type="date">`).

Also, we haven’t really discussed and agreed how to handle unsupported types, like `range`, `file`, `image`, etc. ([full list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input)). 

One option is that we add a `<vaadin-email-field>` to the collection, along with other plausible supported types like `url`, `tel` and `color` (`time` and `datetime` are already in the backlog).

**Comment by samie** [comment]
If the underlying HTML does not support changing the attribute on-the-fly and it behaves more like element, then separate elements would really make sense. It means more projects, API and Flow components, but that should be ok and pretty straight-forward.

**Comment by bennypowers** [comment]
I heartily support this issue, particularly for `type`s which will never get their own input component, like `email` or maybe `phone`.

Please also pass `inputmode` down to the underlying input.

Validation could be handled in the component by providing a default `pattern` derived from the type property

```js
patternFor = type => propOr(defaultPattern, patterns, type)
html`<input type="${supported(type) ? type : 'text'}" pattern="${patternFor(type)}"`
```

Passing this type property down to the input is low-hanging fruit that will benefit many users for minimal effort.

**Comment by tomivirkki** [comment]
Alternative solution would be to make the input slottable.
```
<vaadin-text-field>
  <input type="search">
</vaadin-text-field>
```

This would enable creating text fields that have the native `<input>` exposed instead of hiding it inside the shadow root and thus would work better with native forms & password managers etc

**Comment by jouni** [comment]
That’s a nice idea. Support for password managers sounds rather nice indeed. Is #67 related?

**Comment by heruan** [comment]
What about a new `vaadin-input-field`, where you can slot the desired type? Then `vaadin-text-field` and `vaadin-password-field` can be "shortcuts" of that.

**Comment by web-padawan** [comment]
The prototyping has been done in #274 and the results reported there.

**Comment by web-padawan** [comment]
Closing in favour of #273
