### ISSUE TITLE
Add support for a label "suffix" slot

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field#212]
It would be useful to have support to add components to the label part of a text field to a text field in an unobtrusive manner, e.g. to add additional information or to provide field-related actions.

Use cases:

<img width="262" alt="screen shot 2018-03-30 at 19 33 40" src="https://user-images.githubusercontent.com/851745/38147153-4a01d5ce-3451-11e8-8b4f-2c281deb6886.png">

```html
<vaadin-text-field label="Search">
  <a slot="label-suffix" href="#">help</a>
</vaadin-text-field>

<vaadin-password-field label="New password" required>
  <a slot="label-suffix" href="#">suggest</a>
</vaadin-password-field>

<vaadin-combo-box label="Choose user" required>
  <a slot="label-suffix" href="#">me</a>
</vaadin-combo-box>
```

See: https://jsfiddle.net/heruan/nry6nu00/

**Comment by jouni** [comment]
Is there possibly a more general use case here, about customizing the whole label, and not just the suffix?

At least I have considered that the current `<vaadin-text-field label="...">` attribute is just a convenience API for setting the text content of a label slot internally.

Perhaps the suffix use case is the most common one, but I can at least think of a use case that I want to provide an icon before the label text which seems fairly common as well.

So maybe it should be `slot="label"` instead?

```html
<vaadin-text-field>
  Search <a slot="label" href="#">help</a>
</vaadin-text-field>
```

This forces users to provide some additional CSS to align the link to the end, and possibly to handle the required indicator somehow as well. But I feel like we should consider this more generic use case.

**Comment by heruan** [comment]
I agree with the more generic `label` slot, but I'd still keep the `label-suffix` slot as a convenient way to avoid this:

> This forces users to provide some additional CSS to align the link to the end, and possibly to handle the required indicator somehow as well.

What do you think?

**Comment by jouni** [comment]
I’m not keen on having too many slots. I’m concerned about the complexity and performance implications it could mean. Also, are nested slots supported?

To align the suffix in my previous example, this should be enough:

```html
<dom-module id="text-field-label-suffix" theme-for="vaadin-text-field">
  <template>
    <style>
      [part="label"] {
        display: flex;
        justify-content: space-between;
      }
    </style>
  </template>
</dom-module>
```

For the required indicator, perhaps we have a special attribute you can add to an element to indicate that it should be used:

```html
<vaadin-text-field>
  <div slot="label">
    <span required-indicator>Search</span>
    <a href="#">help</a>
  </div>
</vaadin-text-field>
```

**Comment by heruan** [comment]
Now that 2.0 has been released, any chance for #213 to be reconsidered as new feature?

**Comment by abdonrd** [comment]
I have another need! Something like `sub-label` slot?

![screenshot 2019-02-07 at 16 51 53](https://user-images.githubusercontent.com/1007051/52423576-afba7800-2af8-11e9-86ca-7bc864ebff44.png)

**Comment by moderndeveloperllc** [comment]
> I have another need! Something like `sub-label` slot?
> 
> ![screenshot 2019-02-07 at 16 51 53](https://user-images.githubusercontent.com/1007051/52423576-afba7800-2af8-11e9-86ca-7bc864ebff44.png)

Would need to address the positioning of a `sub-label` or `label-suffix` slot - above/below/left/right of the field, etc.

**Comment by jouni** [comment]
In my view, that’s a description text, and I’ve been thinking we should add that in addition to the current `error-message`.

I think the description text has a bit different semantics than the original idea @heruan proposed, which isn’t really a label, though, more like a supplementary action.

**Comment by heruan** [comment]
I agree with @jouni, that looks like more of a description or "help text"  and it might be better placed *below* the field (or even used as the placeholder); neither my idea of a supplementary action slot should be part of the label, anyway.

What about something like

```html
<label>[[label]]</label> <div part="action"><slot name="action>"</slot></div>
<input>
<div part="description"><slot name="description"></slot></div>
```

One then could tune `flex-order` to move e.g. `description` between the label and the field.

**Comment by abdonrd** [comment]
I also agree with @jouni! Description text makes more sense for my use case!

**Comment by heruan** [comment]
Here I am again poking on this 🙂 I'd really like for the feature to be included in future releases of any component which has a label, since any other workaround I'm trying isn't quite satisfying. I don't know if this is the right repo for this feature, maybe `lumo-styles` is more fit whit a mixin?

**Comment by heruan** [comment]
I gave another shot at this! With this change:

```diff
-      <label part="label" on-click="focus" id="[[_labelId]]">[[label]]</label>
+      <div part="label-container">
+        <label part="label" on-click="focus" id="[[_labelId]]">[[label]]</label>
+        <div part="label-suffix"><slot name="label-suffix"></slot></div>
+      </div>
```

and this style (I would add it to `required-field` mixin or a new one):

```css
      [part="label-container"] {
        display: flex;
        justify-content: space-between;
        line-height: 1;
        font-size: var(--lumo-font-size-s);
      }
```

this is the result: https://mire-tea.glitch.me/

**Comment by web-padawan** [comment]
Not when we have [vaadin-custom-field](https://github.com/vaadin/vaadin-custom-field), I would recommend doing the following trick instead:

1. Create your own `my-custom-field` which would extend `vaadin-custom-field`

2. Tweak the template of `my-custom-field` and add the slots you need there

3. Wrap all the controls you want to look like that in `my-custom-field`

Would that work for your use case? This is generally how the Custom Field is supposed to be used. 
Baking such an opinionated functionality in `vaadin-text-field` is something we'd like to avoid.

**Comment by heruan** [comment]
Thank you @web-padawan for the feedback! I've considered extending `vaadin-custom-field`, but then the feature won't be available to components which use `vaadin-text-field` (e.g. the password/number variant or `vaadin-combo-box`); having this here would propagate the feature to them.

I consider the custom-field a great component to create new type of fields, while  I feel more as an overkill to use it just to add a slot to an existing implementation.

I understand your concerns and I promise I won't return on this again if you decide to avoid adding this feature. I tried not to be much opinionated: just a slot side-by-side with the label, to be able to use that space.

**Comment by web-padawan** [comment]
> I've considered extending vaadin-custom-field, but then the feature won't be available to components which use vaadin-text-field (e.g. the password/number variant or vaadin-combo-box); 

My idea from the comment above is that you would wrap any components where you need "label suffix" feature into `my-custom-field`, instead of using own labels of those components.

That might be challenging for Material (as there `vaadin-custom-field` implies usage of always floating label and contains specific CSS tricks targering proper alignment).

> having this here would propagate the feature to them.

That's exactly what personally I would prefer to avoid. Baking extra slot into any component would result in a higher level of abstraction, whereas Vaadin components aim to be less opinionated.

**Comment by heruan** [comment]
> My idea from the comment above is that you would wrap any components where you need "label suffix" feature into `my-custom-field`, instead of using own labels of those components.

I've tried: the custom-field has some quirks, e.g. label is not highlighted when the wrapped field is focused and clicking on the label doesn't focus the wrapped field.

But I get your take, it makes sense; I'll try to work this out by other means. Feel free to close this and the PR!

**Comment by web-padawan** [comment]
Thanks for sharing the feedback, and feel free to submit those issues you described to `vaadin-custom-field`. We could include them into the set of fixes to land before V14 stable is out.

Closing per above comment.
