### ISSUE TITLE
prefix & suffix are received when using iron-form

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-text-field#216]
When I use it in a form, the `event.detail` has `prefix` & `suffix` as `undefined`.

**Comment by samiheikki** [comment]
Tried this and cannot reproduce with current master with the following code block:
```
<iron-form id="form1" method="get">
      <form>
        <vaadin-text-field name="text-field">
          <div slot="prefix">$</div>
          <div slot="suffix">€</div>
        </vaadin-text-field>
        <vaadin-button onclick="form1.submit()">Submit</vaadin-button>
      </form>
    </iron-form>
    <script>
      form1.addEventListener('iron-form-submit', function(event) {
        console.log(event.detail);
      });
    </script>
```

**Comment by samiheikki** [comment]
Discussed with @tomivirkki and decided to close the ticket.

Issue is only reproducible if removing `name` attribute from a component with named slots (like vaadin-text-field) so the issue is due to iron-form.

**Comment by moderndeveloperllc** [comment]
@samiheikki, @tomivirkki I'm getting the same issue when using `iron-form`'s `serializeForm()` which appears to be [explicitly ignoring `slots`](https://github.com/PolymerElements/iron-form/blob/e5f66f79a4455123baa7e3322083938d1b9dc9f7/iron-form.js#L455).
```
<iron-form id="userForm">
  <form>
    <vaadin-form-layout .responsive-steps="${this.steps}">
      <vaadin-text-field id="username" name="username" label="Username" required .value="${this.username}"></vaadin-text-field>
    </vaadin-form-layout>
  </form>
</iron-form>

const userForm = this.shadowRoot.getElementById('userForm');
userForm.addEventListener('iron-form-submit', (event) => {
      event.preventDefault();
      console.log(userForm.serializeForm());
    });
```
result: `{username: "moderndeveloperllc", prefix: undefined, suffix: undefined}`

Any thoughts on why these slots are being picked up?
