### ISSUE TITLE
Click handling within TextField

### ISSUE THREAD

**Issue by syampillai** [vaadin/vaadin-text-field#225]
Currently, clicking anywhere inside the TextField (including its prefix/suffix components) brings the focus to it. I have a prefix component on ComboBox that, when clicked, requires to pop up another user-interface for a separate user interaction. However, ComboBox gets opened when this happens and I need to close it programmatically (Also, closing the ComboBox programmatically causes a flicker on the screen.)

**Comment by web-padawan** [comment]
Closing as duplicate of #125. In the meanwhile, workaround from the above comment can be used.
