### ISSUE TITLE
It should be possible to react to user input immediately

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#233]
When the end-user is typing in the field it should be possible to react to each new character in the input field.

The native `input` event on the `<input>` element is for this purpose. The difference to the `change` event is that the `input` event is fired without the need to blur the field or press Enter. The events are the same in the sense that they are only fired for end-user input, not for programmatic updates.

It is possible to react immediately to changes with the `value-change` event, however, you don't know if the event is user-originated.

**Comment by Borjagodoy** [comment]
Any news about this issue?, i think that with lit-html is necessary this functionality. In lit without two data binding, is impossible detect the change in the value of input without this event.

**Comment by tomivirkki** [comment]
@Borjagodoy Polymer's 2-way data-binding in based on `{propertyName}-changed` events so you still get a `value-changed` event from the field whenever its `value` changes. However, as mentioned above, there's no way to know if it was user-originated.

**Comment by platosha** [comment]
With exception of the clear button (see #347), this is working out-of-the-box already:
- we use an `<input>` inside, it fires `input` events natively
- by standard, they are bubbling and composed, so they propagate up and be listened on the `<vaadin-text-field>` host already
- `<vaadin-text-field>` does not stop their propagation
