### ISSUE TITLE
change text field height?

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-text-field#235]
Is there a way to change the height of vaadin-text-field?
Width ca be changed by setting the `width` property. But how can I change the height?

**Comment by web-padawan** [comment]
Thanks for the issue, and sorry for not answering earlier. If you are using Lumo theme, you can use ` --lumo-text-field-size` to change the height, as the "small" theme variation already does: https://github.com/vaadin/vaadin-text-field/blob/6598e800775e18ce9f927fd780c7371a2caa0347/theme/lumo/vaadin-text-field-styles.html#L292

If you are creating your own custom theme, you can implement own CSS, the correct places to edit are these ones:
- `:host::before` should be used to apply styles to align the baseline with other elements (like buttons)
- `[part="input-field"]` should be used to edit the height of the underlying text-field

**Comment by mvysny** [comment]
I hoped that the text field would do this automatically - e.g. when I call `textField.setHeight("300px");` on server-side, that the text field contents would accommodate for the new size (like in Vaadin 8) and I will not have to also set the `--lumo-text-field-size` property as well.
