### ISSUE TITLE
text field is way too high by default

### ISSUE THREAD

**Issue by torstenwerner** [vaadin/vaadin-text-field#237]
Hi,

a simple text field takes the full screen height. Version is 2.0.1 and browser is chrome. How is it supposed to be styled correctly? I am attaching a screenshot and a sample file:

    <html>
    <head>
        <title>Test</title>
        <link rel="import" href="../bower_components/vaadin-text-field/vaadin-text-field.html">
    </head>
    <body>
    <vaadin-text-field label="Label" value=""></vaadin-text-field>
    </body>
    </html>

![bildschirmfoto 2018-07-03 um 15 26 21](https://user-images.githubusercontent.com/1051357/42222509-b5c6a90a-7ed5-11e8-806e-7a955f31f6de.png)

**Comment by tomivirkki** [comment]
Remember to include `<!DOCTYPE html>` at the very beginning of the document.

**Comment by torstenwerner** [comment]
Ok it feels like a strange solution to me but it works. Thank you!

**Comment by ztzven** [comment]
Such a random solution; worked though!

**Comment by tomivirkki** [comment]
Not really random. Missing the DOCTYPE will result in browsers using a different rendering mode that is incompatible with some specifications.

http://w3c.github.io/html/syntax.html#the-doctype

So in practice, DOCTYPE should _always_ be defined in the beginning of an html file.
