### ISSUE TITLE
Labels should not define a top margin

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field#239]
Same as https://github.com/vaadin/vaadin-form-layout/issues/85

> Labels of form items set a `margin-top: var(--lumo-space-m)` on themselves. Items should not care about that, since they don't know what might be around them. I understand this is intended to create a gap between items, but then the first item in the form will have a useless top margin.
>
> In my opinion, the layout element should care about spacing its own items, not the items themselves.

In this case, it defines `margin-top: calc(var(--lumo-font-size-s) * 1.5)`.

**Comment by platosha** [comment]
I would oppose. The space above the label is not useless, it is meaningful.

One of the key visual design principles is that distance between things defines relationships. Things that are highly related should be close, things that are not related should be placed far apart from each other.

The label is related to the labelled item more than to anything else. So it should always be distanced from the rest elements to maintain this visual relationship. The margin above the label does exactly that.

Using multiple `<vaadin-text-field>` stacked inside a plain div, not a layout, is a valid use case. It should not result in confusing output about what the labels belong to. Thus we cannot delegate all the spacing work to layout components.

**Comment by heruan** [comment]
Thank you @platosha for the feedback! The motivation is clear. The problems I see here are that:

1. the element *assumes* there is something preceding itself, so you get space you don't need when the element is e.g. the first child;
2. if you use the element in a layout which takes care of the spacing, you also get space you don't need.

Of course the use case of fields stacked in a plain `div` is valid, but in such a "vanilla" use case I'd prefer to have a "vanilla" style too, i.e. no spacing, to let the developer decide how to space (e.g. with `display: grid` or third part framework).

To have beautiful spacing by default, Vaadin's already provide its own vertical and horizontal layouts with ad-hoc styles (i.e. `theme="spacing"`).

**Comment by web-padawan** [comment]
Here is how you can reset padding for the text-fields, if you need:

```html
<dom-module id="no-label-padding" theme-for="vaadin-*-field">
  <template>
    <style> 
      :host([theme~="no-label-padding"][has-label]) {
        padding-top: 0;
      }
    </style>
  </template>
</dom-module>
```

The `theme` attribute propagation allows to propagate it inside the components using text-field internally (combo-box, date-picker, select, time-picker) so the appearance would be consistent.

Given the above, let me close as won'tfix per https://github.com/vaadin/vaadin-text-field/issues/239#issuecomment-404856452
