### ISSUE TITLE
Using vaadin-text-field in script module

### ISSUE THREAD

**Issue by hyyan** [vaadin/vaadin-text-field#247]
I have tried to use `vaadin-text-field` in script module, but it fails with the following message

> Uncaught TypeError: Failed to resolve module specifier "@vaadin/vaadin-lumo-styles/color.js". Relative references must start with either "/", "./", or "../".

Is this expected behavior, and how to make it work

Here is my code : 

```
  <script type="module">
    import {PolymerElement, html} from './node_modules/@polymer/polymer/polymer-element.js';
    import './node_modules/@vaadin/vaadin-text-field/theme/lumo/vaadin-text-field.js';

    class MyElement extends PolymerElement {

      static get properties() { return {}; }

      static get template() {
        return html`
          <vaadin-text-field></vaadin-text-field>
        `;
      }
    }

    customElements.define('my-element', MyElement);
  </script>
  
  <my-element></my-element>
```

**Comment by hyyan** [comment]
As this is a question , I moved it to StackOverflow

**Comment by web-padawan** [comment]
Hi, you can read about ES modules and "bare module specifiers" here: https://www.polymer-project.org/3.0/docs/es6

**Comment by hyyan** [comment]
@web-padawan thanks for your comment, I know about "Bare" import specifiers". what puzzled me is why polymer import worked and the element import did not. now I have a better idea. I moved the question [here](https://stackoverflow.com/questions/51892776/how-to-use-vaadin-text-field-in-script-module) in case you have time to write an answer
