### ISSUE TITLE
How to hide the error-message from javascript?

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-text-field#249]
Is there a way to remove the error message in vaadin-text-field?
I have a checkbox and a vaadin-text-field. Clicking the checkbox enables the text field. If I leave the text field empty, then an error-message appears(as expected). But I want the message gone when the field is disabled(which is when I click the checkbox again). Is there any API for doing this?

**Comment by tomivirkki** [comment]
You can control the `invalid` property of the component programmatically. Alternatively you could use the [theming mechanism](https://github.com/vaadin/vaadin-themable-mixin/wiki) to hide the error message.
