### ISSUE TITLE
Prefix and Suffix

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#25]
Use Cases to cover:
- allow adding icons/buttons inside the focusable area (think of combo-box)
- consider disabling "floating label" when prefix is defined

**Comment by limonte** [comment]
The simple example: http://codepen.io/swhdesigns/pen/bNwVgG

**Comment by jouni** [comment]
Two specific use cases, adding an icon for invalid or valid text fields:

<img width="238" alt="screen shot 2017-03-15 at 10 57 43" src="https://cloud.githubusercontent.com/assets/66382/23940644/6f2377cc-096e-11e7-94d8-3752180fb0aa.png">

Draft code:

```html
<vaadin-text-field invalid="{{invalid}}">
  <img src="cross.svg" slot="suffix" hidden$="[[!invalid]]">
  <img src="check.svg" slot="suffix" hidden$="[[invalid]]">
</vaadin-text-field>
```
