### ISSUE TITLE
TextArea does not updateHeight when display none is removed

### ISSUE THREAD

**Issue by brp-helena** [vaadin/vaadin-text-field#254]
I have a TextArea that is part of a container that is hidden with display:"none" as standard.
 When the user opens the page, data is _loaded_ to this TextArea and
_updateHeight is called and calculates the inputHeight to zero since the component is not displayed. 

Later when an action from the user removes display:"none" _updateHeight is not called again and the TextArea do not grow to fit the text as expected.

Example:

@HtmlImport("styles/shared-styles.html")`
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        final Div hiddenDiv=new Div();
        TextArea field = new TextArea();
        field.setValue("Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
                "Nam ornare risus at diam vehicula, a euismod ipsum dictum. Donec ut euismod dolor.\n" +
                "Mauris sit amet nisl nec quam pulvinar mollis. Fusce sit amet nisi est.\n" +
                "Suspendisse commodo hendrerit tincidunt. Sed ac suscipit felis.\n" +
                "Suspendisse faucibus ultrices diam, sit amet suscipit sapien tristique in.");
        hiddenDiv.add(field);
        hiddenDiv.getStyle().set("display", "none");
        Button button = new Button("show", event -> {
            hiddenDiv.getStyle().remove("display");
        });
        add(button, hiddenDiv);
        setClassName("main-layout");
    }
}

**Comment by web-padawan** [comment]
Thanks for the issue. We recently fixed similar one but for different component: vaadin/vaadin-form-layout#90 so my guess is that we should also implement this approach here.

**Comment by tomivirkki** [comment]
Since this "invoke on appear" -feature is quite requested here and there (this, form-layout, grid, flow grid editor), should we just add it to the element mixin? Did a quick prototype a while ago: https://github.com/vaadin/vaadin-element-mixin/tree/when-attached-proto The proto has bad API (should dispatch an "appear" event or something instead) but the concept is still valid.
