### ISSUE TITLE
Input e-mail on mobile browser

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field#260]
When an `<input>` has `type="email"` in major mobile browser the on-screen keyboard adapts to facilitate typing e-mails. It would be great to have this also in `vaadin-text-field` (similar also other type shows specific keyboard).

**Comment by web-padawan** [comment]
Thanks for the issue. This appears to be duplicate of #204 so I'm closing this for now.
One potential solution would be to implement #67 in the future version of component.
