### ISSUE TITLE
move SlotHelpers to vaadin-core

### ISSUE THREAD

**Issue by michaelmosmann** [vaadin/vaadin-text-field#263]
### Description
code from com.vaadin.flow.component.textfield.SlotHelpers should moved to core and make access public

### Expected outcome
can use SlotHelpers method to handle slot-related stuff

### Actual outcome
code duplication

**Comment by limonte** [comment]
Hello @michaelmosmann 

Since the issue is related to Flow component, could you please move it to https://github.com/vaadin/vaadin-text-field-flow

Thank you.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-text-field-flow#117
