### ISSUE TITLE
Prevent invalid input

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#27]
Use cases:
- applies only to sync validation
- opt-in feature to prevent user from typing values that would be invalid
- should of course work with custom validators also
- `iron-input` has a corresponding property called `prevent-invalid-input`

**Comment by jouni** [comment]
I’d be willing to trade this feature for #16. I have an initial proto for the feature that I’ve been thinking that would cover that use case: https://github.com/vaadin/vaadin-input/tree/proto/validation-feedback

**Comment by jouni** [comment]
paper-input has `allowed-pattern` also, which does the same thing. Not exactly sure which one is better, to have a separate property for this, or to use the other validation properties.
