### ISSUE TITLE
Prototype slotted input (1d)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#274]
child of #273

FInd out what's required to make this work with 
- text field
- text area
- passowrd field

**Comment by web-padawan** [comment]
Prototype: https://github.com/vaadin/vaadin-text-field/compare/proto/slotted-input

Questions to discuss:

1. should we support also slotted `<label>`? 
- Pros: 
  - slotted `<label>` would allow user to set `aria-labelledby` property himself
  - slotted `<label>`would allow to use `for` attribute and `in` on the input
- Cons:
  - It would require us to revert #257 and move label styles back here (unless we also want to support in checkbox-group and radio-group)

2. should we whitelist allowed types of `input`?

It does not make much sense to accept e.g. `<input type="color">` which have totally different appearance and their own states, which might not work nicely with our component.

3. should we support also slotted error message? The only purpose would be A11Y, as we set the `id` on it which is used for the `aria-describedby` on the native input in the shadow root.

4. should we observe attribute mutations on the slotted input? 

- What if the user sets e.g. `required` on the slotted input, but not on the host element? 
- What to do with some custom attributes, like `step` on the `<input type="number>"`

**Comment by web-padawan** [comment]
## Suggestions:

1. Allow user to slot the `input` without having to move any attributes to it (only set `type` and `slot`)

2. Refactor test suites properly to test against shadow / slotted input 

3. Refactor observers for propagating `required`, `invalid` etc (make them DRY)

4. Document that only subset of supported `input` properties is propagated to the slotted input

5. Emphasise using native input properties, like `placeholder` (it does not make sense to propagate them). Follow the same idea as we previously did for renderers, to replace all the demos eventually

6. Host properties like `autocorrect` etc to be deprecated in the next major release

**Comment by tomivirkki** [comment]
Also, allow adding the input lazily. It's not guaranteed that the `<input>` is included inside the `<vaadin-text-field>` when the text field gets connected/initialized.

Someone might build the dom programmatically by first creating a `<vaadin-text-field>` and then including an `<input>` separately; IIRC some templating frameworks do this internally.

**Comment by web-padawan** [comment]
The prototype implementation uses getter for now. Adding lazily (and possibly, removal) would basically mean the need for `FlattenedNodesObserver` there we could update both the node which `focusElement` is referencing, and set any attributes etc.

**Comment by web-padawan** [comment]
Closing, the implementation to be done in #281
