### ISSUE TITLE
Error. Already being initialized and vaadin-text-field by required-field?

### ISSUE THREAD

**Issue by adexerivera** [vaadin/vaadin-text-field#275]
### Description

Since 2.1.3 there is one error when load this library, "Application ROOT-2521314 is already being initialized and vaadin-text-field" this error is showed on this image: 

![capturachrome](https://user-images.githubusercontent.com/1585009/48261245-51f19380-e416-11e8-9bc6-64ff8ce03b26.PNG)

and it's not posible load page, we think that it happens since that was imported required-field on commit "Update text-field styles to use required field mixin".

### Expected outcome

Show page normally.

### Actual outcome

Not show antything.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge
- [x] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Closing per above comment.
