### ISSUE TITLE
Implement slotted input feature

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-text-field#281]
Child of #273

The slotted input should work with both text-field and password-field. Slotted textarea should work with text-area.

1. Allow user to slot the `input` without having to move any attributes to it (only set `type` and `slot`)

2. Refactor test suites properly to test against shadow / slotted input 

3. Refactor observers for propagating `required`, `invalid` etc (make them DRY)

4. Document that only subset of supported `input` properties is propagated to the slotted input

5. Emphasise using native input properties, like `placeholder` (it does not make sense to propagate them). Follow the same idea as we previously did for renderers, to replace all the demos eventually

6. Allow adding the input lazily. It's not guaranteed that the `<input>` is included inside the `<vaadin-text-field>` when the text field gets connected/initialized.

Prototype at #274

**Comment by jmart1** [comment]
How exactly do we make use of this from our Java code?  I want to utilize this phone example:

```
        <vaadin-text-field label="Phone">
          <input type="tel" slot="input" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" placeholder="Format: 111-222-3333">
        </vaadin-text-field>
```

but from within my Java code.  Is that possible?

**Comment by jmart1** [comment]
Came up with a way to accomplish setting the type to tel.

```
                UI.getCurrent().getPage().executeJs(
                        "document.getElementById(\"" + id + "\").shadowRoot\n" +
                                ".querySelector(\".vaadin-text-field-container\")\n" +
                                ".getElementsByTagName(\"div\")[0]\n" +
                                ".getElementsByTagName(\"slot\")[1]\n" +
                                ".getElementsByTagName(\"input\")[0]\n" +
                                ".setAttribute(\"type\", \"tel\");"
                );
```

where the variable id is the id on the TextField component.
