### ISSUE TITLE
Autoselect feature

### ISSUE THREAD

**Issue by emarc** [vaadin/vaadin-text-field#288]
### Description
Quite often, if would be desirable to (auto)select the content of the textfield when it is focused, in order to improve UX. 
The most convenient way to achieve this would be to add a `autoselect` attribute, similar to `autofocus` etc.

### Expected outcome
`<vaadin-text-field autoselect>` would cause the input text to be selected automatically when the field is focused. If the users starts typing, the existing content is replaced. User can press arrow-right to append stuff. And so on – you now what I'm talking about :-)

### Actual outcome
No easy way to achieve this ATM. 

### Related
#214 is a request for a selection API.

**Comment by limonte** [comment]
Released in https://github.com/vaadin/vaadin-text-field/releases/tag/v2.3.0-alpha4 🎉
