### ISSUE TITLE
vaadin-text-area does display in Angular

### ISSUE THREAD

**Issue by rampadc** [vaadin/vaadin-text-field#298]
### Description
vaadin-text-area does not appear. No styles are applied to element when rendered.

### Expected outcome
Something akin to examples on Vaadin.

### Actual outcome
Nothing shows up.

### Steps to reproduce

1. Put a `vaadin-text-area` element in the page.
2. Head over to browser Chrome and Firefox behaves the same in this case and inspect the text area.
3. There is nothing between the vaadin-text-area tags unlike other vaadin elements, which have #shadow-root.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge (not tested)
- [ ] IE 11 (not tested)
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

**Comment by samiheikki** [comment]
Have you imported `vaadin-text-area.html`?

**Comment by rampadc** [comment]
Oh you need to import vaadin-text-area explicitly. That's strange. Yea it shows up now. Thanks.
