### ISSUE TITLE
Extra native "reveal password" button in vaadin-password-field with IE11/Edge

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/vaadin-text-field#315]
### Description
In IE11/Edge extra "reveal password" button natively shown.

### Expected outcome
Only one "reveal password" button is displayed

### Actual outcome
https://pasteboard.co/I0Fwr3Oy.png

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [x] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Note that it was previously fixed by this line but apparently something has changed in Edge:
https://github.com/vaadin/vaadin-text-field/blob/93640baabb67ddc828b8498d90393b4d8ea06d28/src/vaadin-password-field.html#L27
