### ISSUE TITLE
Fix the focus moving in FF 65

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-text-field#318]
**Live Demo:**
https://glitch.com/edit/#!/join/f52bfc06-6f8a-42de-89b2-b4172ea84076

**Note:** Bug occurs on **FF 65**, wasn't occurring on **FF 64**

**Steps to reproduce:**
- Create a custom component.
- Declaratively add several text-fields to it.
- Imperatively create several text-fields and append them to the parent custom element. (i.e in `connectedCallback`)
- Move focus with tab through the text-fields

**Description of the issue:**
Focus is moving to nowhere after focusing the first appended `text-field`
![ff-bug](https://user-images.githubusercontent.com/29372419/52775275-ee47b980-3047-11e9-8cae-2cfdc51a6495.gif)

**Comment by pleku** [comment]
To note here that vaadin/flow#4682 is a BFP and there it is also stated that this broken with buttons too.

**Comment by tomivirkki** [comment]
This is a Firefox issue and can be reproduced with the following example (built with native APIs): https://jsbin.com/niwosobapi/edit

The bug has been reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1528686
