### ISSUE TITLE
It should be possible to override the validate method from the Flow textConnector

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/vaadin-text-field#321]
The fix of this PR [vaadin/vaadin-text-field-flow/pull/116](https://github.com/vaadin/vaadin-text-field-flow/pull/116) is supposed to override the validate method of client-side in case when the field is marked as required from the server side so to resolve this issue in here [vaadin/vaadin-text-field-flow/issues/104](https://github.com/vaadin/vaadin-text-field-flow/issues/104)

The problem is that the validate method of client-side is still called when blured. Not sure about the reason why this happens but a guess would be the fact that the blur event is registered with the validate method when the component is being initialized .

A possible solution to this issue IMO is to have the client side validate method changed to this:
```
   validate() {
      return this.doValidate();
    }
    doValidate(){
      return !(this.invalid = !this.checkValidity());
    }
```

and after that have the Flow textConnector override the doValidate method instead of validate method.

The whole change will also fix [vaadin/flow/issues/3230](https://github.com/vaadin/flow/issues/3230)

**Comment by web-padawan** [comment]
The reason why this happens is this line:
https://github.com/vaadin/vaadin-text-field/blob/48147e5163baff3ca0f710b6bd725f13a532e2e1/src/vaadin-text-field-mixin.html#L509

So, instead of using `this.validate.bind(this)` we should have `blur`listener like that:

```js
_onBlur() {
  this.validate();
}
```

And the line above should be changed like this:
```js
this._boundOnBlur = this._onBlur.bind(this);
```

That would fix the issue without any extra methods.

**Comment by Klaudeta** [comment]
Thanks this is really a cleaner solution than the one I was previously suggesting. In this way there is no need to change anything in the Flow component for the fix to be applied
