### ISSUE TITLE
Required indicator is announced by screen readers (VoiceOver)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#325]
VoiceOver announces the required indicator character after the label text. For example:

```html
<vaadin-text-field label="Label"></vaadin-text-fiel>
```
VoiceOver announces:
```
Label bullet, edit text
```

This happens even if a field is not marked as being required.

### Expected outcome
Only the actual label text is announced (“Label” in the previous example).

**Comment by web-padawan** [comment]
Possibly duplicate of #221 ?

**Comment by jouni** [comment]
Ah, indeed a duplicate.
