### ISSUE TITLE
Setting both value and step in number field truncates a valid value

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-text-field#331]
### Description
When setting both `value` and `step` with decimals the initial value is modified even though it's valid

### Expected outcome
Value is not modified and `9.99` is shown

### Actual outcome
Value is modified and shown as `10.0`

### Demo
The following snippet can be used to reproduce the issue
`<vaadin-number-field value="9.99" step="0.01" label="value and step"></vaadin-number-field>`
![image](https://user-images.githubusercontent.com/9820084/53397341-8e3e0500-39af-11e9-9999-345f7a570f23.png)

**Comment by alvarezguille** [comment]
Fix for this should also be checked in the flow integration due to vaadin/vaadin-text-field-flow#147

**Comment by tomivirkki** [comment]
This should be fixed so that the behaviour aligns with native input (number) = The value can be programmatically set as any number, step is considered in validation but it shouldn't prevent setting the value to something else (programmatically).
