### ISSUE TITLE
"change" event is not triggered if the value is cleared programmatically by calling "clear()"

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-text-field#346]
### Description
`vaadin-text-field` doesn't trigger the `change` event if `myTextField.clear()` is called to clear the value (when the value was not already empty). I'm not 100% sure if this is expected, but in my opinion it would make sense to trigger the event also when `clear()` is called and it would be more consistent. Especially since `clear()` is public API.

I can imagine that in some cases when programmatically clearing the value, you might want to suppress the `change` event, but I think that would be another feature (if needed). That could be made possible using an optional parameter for the `clear()` method (or a new method only for that).

This is related to #344 and #345. The code could probably be changed so that the `clear()` method always sends the custom `change` event

### Expected outcome
`vaadin-text-field` should trigger the `change` event also in this case imo.

### Actual outcome
The `change` event is not triggered.

### Live Demo
Can be reproduced in https://cdn.vaadin.com/vaadin-text-field/2.3.5/demo/#text-field-basic-demos

### Steps to reproduce
1. Open the browser dev tools inspector
2. Make sure your JS console log level includes "Info" level.
3. Select some `<vaadin-text-field>` with the inspector.
4. Run:  
    ```js
    $0.addEventListener('change', e => console.log('vaadin-text-field change: ', e))
    ```
5. Make sure the text field has some value other than empty string (type in it if needed and hit Enter or unfocus the field to confirm the value change).
6. Run: `$0.clear()`
7. Notice that the `change` event is not triggered when calling `clear()` (no message logged to console).

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

Tested on macOS Chrome, but this most probably affects all browsers that can be used with a keyboard since it's an error in component logic.

**Comment by tomivirkki** [comment]
"change" events should only occur in result of a user action https://developer.mozilla.org/en-US/docs/Web/Events/change

**Comment by Haprog** [comment]
Ok, I guess the current behaviour regarding this is fine then.
