### ISSUE TITLE
Patterns seem to be ignored on number field

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-text-field#350]
I want the user to only be able to type in integers into a number field. If I set `pattern=[0-9]*` and `preventInvalidInput=true`, I can still type `46...1`, which of course is not a valid integer and doesn't match the regex.

**Comment by tomivirkki** [comment]
The number field is based on the native `<input type="number">`. Because it also allows you to input `46...1`, Vaadin's number field has the same limitation

**Comment by Kurren123** [comment]
I see. Thanks for taking the time to explain.
