### ISSUE TITLE
Allow setting "rows" and "cols" for TextArea

### ISSUE THREAD

**Issue by Springrbua** [vaadin/vaadin-text-field#351]
A `textarea`-element has the properties `rows` and `cols`, which allow you to specify the visible number of lines and the visible width of the `textarea`.
The `vaadin-textarea` doesn't offer an API to set those values for the nested `textarea`-element.
The issue #170 might be related to this, but it is about setting min/max height, which is already possible using CSS.

**Comment by tomivirkki** [comment]
The `cols` property wouldn't bring that much additional value (especially with proportional fonts) as you can already set the CSS `width` of the element (with units relative to the font-size if you will).

Closing this in favour of #170 as it's more robust by allowing you to also define min/max rows. Setting min/max rows to the same value would effectively be the same as setting one static `rows` value.
