### ISSUE TITLE
vaadin-number-field template undefined for subsequent calls

### ISSUE THREAD

**Issue by asyncLiz** [vaadin/vaadin-text-field#360]
### Description

I believe this is just an oversight, but the memoized template value of `<vaadin-number-field>` is not returned on subsequent calls. This makes it impossible to extend the number field in a subclass.

### Expected outcome

`NumberFieldElement.template` should return the element's template. It looks like [`return memoizedTemplate;`](https://github.com/vaadin/vaadin-text-field/blob/master/src/vaadin-number-field.html#L173) should just be moved down one line outside of the if block to fix it.

### Actual outcome

Returns template the first time, then undefined subsequent times.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by web-padawan** [comment]
Nice catch, thanks. Will fix.

**Comment by asyncLiz** [comment]
If you want me to make a PR for it, I'd be happy to do so!

**Comment by web-padawan** [comment]
Fixed by 94142f6, and also cherry-picked to `2.3` branch.
