### ISSUE TITLE
On right to left pages first character of the field is blurred.

### ISSUE THREAD

**Issue by ashksh** [vaadin/vaadin-text-field#364]
### Description
When document is Right to Left, first character of the text value is blurred. 
There is a mask image: 
` --_lumo-text-field-overflow-mask-image: linear-gradient(to left, transparent, #000 1.25em);` when direction is RTL I think it should be: 
` --_lumo-text-field-overflow-mask-image: linear-gradient(to right, transparent, #000 1.25em);`

### Expected outcome
The first character should be clear.

### Steps to reproduce
1. Add `dir="rtl"` to `html` tag
2. Put a `vaadin-text-field` element in the page.
3. Type something into it.

### Browsers Affected
At least:
- [x] Chrome
- [x] Firefox

**Comment by web-padawan** [comment]
Fixed by #448 and released as 2.6.0 alpha.
