### ISSUE TITLE
Noob question: capture the change event when inheriting

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-text-field#374]
I'm trying to make a `console` custom element which inherits from vaadin text area. Whenever any text is changed in the console I want the scrollbar to scroll to bottom. How to I capture the `change` event when inheriting the `TextAreaElement`? This is what I have so far but doesn't work:

```JavaScript
import { TextAreaElement } from '@vaadin/vaadin-text-field/src/vaadin-text-area.js';
import '@vaadin/vaadin-text-field/theme/lumo/vaadin-text-area.js';


class MyConsole extends TextAreaElement {
  constructor() {
    super();

    var me = this;
    me.addEventListener('change', () => { console.log('value changed') })
  }

}

customElements.define('my-console', MyConsole );
```

**Comment by tomivirkki** [comment]
You might want to use "value-changed" event instead. "change" occurs only when a user changes the value and moves the focus away from the field.

**Comment by Kurren123** [comment]
@tomivirkki thank you very much, that worked. Do you know how I can set the scroll position? Setting `scrolltop` doesn't seem to work. Thanks again

**Comment by tomivirkki** [comment]
The component itself doesn't have a public scrollTop API. You can try `textArea.shadowRoot.querySelector("[part=input-field]").scrollTop = 100`, but as said, it's not public. Closing, as this is not an issue but a question.
