### ISSUE TITLE
Setting the height when readonly is True makes the border go funny

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-text-field#375]
If I have the following:

```html
<vaadin-text-area readonly style="max-height: 200px"></vaadin-text-area>
```

And then add some text through code, it looks like this:

![image](https://user-images.githubusercontent.com/3525980/57848780-98fb7f80-77d1-11e9-963f-0fb125bc4508.png)

Am I doing something wrong? Thanks!

**Comment by web-padawan** [comment]
Thanks, confirmed the issue. This is a result of a border applied to a pseudo element which is positioned absolutely. Will submit a PR to change how it's implemented.
