### ISSUE TITLE
NumberField allows [e] character to get typed

### ISSUE THREAD

**Issue by nrapel** [vaadin/vaadin-text-field#376]
While the NumberField disabled input for letters and invalid characters, the **e** character is allowed to get typed in. Also you can type in many **.** characters (and not just one). 

i.e. at the following example
`NumberField field = new NumberField();
numberField.setStep(1);
numberField.setMin(1);
numberField.setMax(65565);
`
By typing in **eeeeee....** you get the following view:

![numberfield](https://user-images.githubusercontent.com/32927980/57865320-09bc8f00-7806-11e9-95eb-3574498b60f5.png)

Normally you shouldn't be allowed 
a) to add the [e] character within a field
b) to add more than one commas 

Checked on FireFox and Chrome, have the same behavior.

**Comment by tomivirkki** [comment]
This is because the number field is based on the native `<input type="number">` that also allows it.

**Comment by nrapel** [comment]
OK that explains a lot and the fact that it allows multiple . characters as well as Firefox allows all kind of characters while Chrome allows only the e character..

**Comment by mvysny** [comment]
Hi, the current behavior as of Vaadin 14.3.2 is a bit inconsistent, as can be tested at https://vaadin.com/components/vaadin-number-field/java-examples/number-field :

* Chromium 84: In addition to numbers, you can only type `e` into the "basic number field". However you can't type `e` into the "Integer field".
* Firefox 79: In addition to numbers, Firefox allows you to type anything into the "basic number field", however you can only type letters into the "Integer field"

Is there some additional guard (JavaScript perhaps) for the `IntegerField`, preventing invalid input?
