### ISSUE TITLE
[material] label overflow

### ISSUE THREAD

**Issue by realansgar** [vaadin/vaadin-text-field#388]
### Description
A label that is longer than the text field itself breaks out of the container.

### Expected outcome
The label should be truncated. This happens already in the lumo theme and in the similar [paper-input element](https://www.webcomponents.org/element/@polymer/paper-input).

### Actual outcome
The label is as long as it's text content and overlays neighbouring elements.

### Live Demo
![Screenshot from 2019-06-19 16-43-16](https://user-images.githubusercontent.com/39188180/59775370-61409580-92b1-11e9-90e4-b75026013455.png)

### Steps to reproduce
1. Put a `vaadin-text-field` element in the page with a label longer than it's width.

### Browsers Affected

- [x] Chrome
_tested only in chrome, but any browser should be affected_

### Possible Fix
Inspired by the [paper-input element](https://www.webcomponents.org/element/@polymer/paper-input).
Add this snippet to `theme/material/vaadin-text-field-styles.html`:
```
:host([has-label]:not([has-value]):not([focused]):not([invalid]):not([theme~="always-float-label"])) [part="label"] {
    ...
    width: 100%;
}

[part="label"] {
    ...
    width: 133%;
}
```

**Comment by web-padawan** [comment]
Thanks for the issue and the suggested fix. Tried it and seems to work nicely, will submit a PR.
