### ISSUE TITLE
vaadin-password-field does not work in Angular

### ISSUE THREAD

**Issue by mpschaeuble** [vaadin/vaadin-text-field#396]
### Description
Adding a vaadin-password-field in an angular-cli bootstrapped throws an exception at runtime (depending on the version only in prod build OR in prod and dev build).

### Steps to reproduce
1) clone https://github.com/vaadin/base-starter-angular
2) Add <vaadin-password-field></vaadin-password-field> to app.component.html
3) Add import '@vaadin/vaadin-text-field/vaadin-password-field.js'; in app.component.ts
4) start application, the following exception is thrown:
`zone.js:682 Unhandled Promise rejection: Object prototype may only be an Object or null: undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object prototype may only be an Object or null: undefined at setPrototypeOf (<anonymous>) at Module.__extends (tslib.es6.js:25) at vaadin-password-field.js:45 at Module../node_modules/@vaadin/vaadin-text-field/src/vaadin-password-field.js (vaadin-password-field.js:156) at __webpack_require__ (bootstrap:83) at Module../node_modules/@vaadin/vaadin-text-field/theme/lumo/vaadin-password-field.js (vaadin-password-field.js:1) at __webpack_require__ (bootstrap:83) at Module../node_modules/@vaadin/vaadin-text-field/vaadin-password-field.js (vaadin-password-field.js:1) at __webpack_require__ (bootstrap:83) at Module../src/app/app.component.ts (0.js:11700) TypeError: Object prototype may only be an Object or null: undefined at setPrototypeOf (<anonymous>) at Module.__extends (http://localhost:4200/vendor.js:77134:5) at http://localhost:4200/0.js:9537:52 at Module../node_modules/@vaadin/vaadin-text-field/src/vaadin-password-field.js (http://localhost:4200/0.js:9648:2) at __webpack_require__ (http://localhost:4200/runtime.js:84:30) at Module../node_modules/@vaadin/vaadin-text-field/theme/lumo/vaadin-password-field.js (http://localhost:4200/0.js:10431:87) at __webpack_require__ (http://localhost:4200/runtime.js:84:30) at Module../node_modules/@vaadin/vaadin-text-field/vaadin-password-field.js (http://localhost:4200/0.js:10501:94) at __webpack_require__ (http://localhost:4200/runtime.js:84:30) at Module../src/app/app.component.ts (http://localhost:4200/0.js:11700:108)`

**Comment by tomivirkki** [comment]
https://github.com/vaadin/base-starter-angular/issues/25#issuecomment-511739770
