### ISSUE TITLE
Please add a helper/hint label

### ISSUE THREAD

**Issue by anezthes** [vaadin/vaadin-text-field#402]
`vaadin-text-field` doesn't have a helper or hint label which makes it difficult to guide users' through forms etc.

The `error-message` slot could potentially be used for this purpose (when the field is not `invalid`).

[Placeholders are simply not good enough](https://www.nngroup.com/articles/form-design-placeholders/).

**Comment by jouni** [comment]
For future reference, there’s [some research](https://adamsilver.io/articles/form-design-from-zero-to-hero-all-in-one-blog-post/) suggesting that a description/help text should be placed below the label, above the field. [Example](http://nostyle.herokuapp.com/examples/registration-form)

The same research suggest the same for error messages as well (place error messages above the field), linking to [another research](http://adrianroselli.com/2017/01/avoid-messages-under-fields.html).

**Comment by rolfsmeds** [comment]
Regardless of placement, this would be super useful as an alternative to placeholders, tooltips etc, especially for mobile where tooltips are not accessible. (I've done at least a couple of custom implementations of this feature in the last three years.)

**Comment by anezthes** [comment]
@jouni for what it's worth, I agree with you regarding the helper placement.

**Comment by Haprog** [comment]
Fixed by #410 available in [v2.6.0-alpha1](https://github.com/vaadin/vaadin-text-field/releases/tag/v2.6.0-alpha1)
