### ISSUE TITLE
Rendering of many TextFields is slow

### ISSUE THREAD

**Issue by Springrbua** [vaadin/vaadin-text-field#405]
### Description
If you have a form with many `TextField`s (`NumberField`s, `DatePicker`s etc. work too), the rendering becomes pretty slow.
The reason for this seems to be a so called [Forced Reflow](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing), caused by TextFieldMixin#__observeOffsetHeight.

### Expected outcome
The method `__observeOffsetHeight` should not cause a poor rendering performance, accessing the `offsetHeight` should not trigger a forced reflow.

### Actual outcome
Accessing the `offsetHeight` inside `__observeOffsetHeight` causes a forced reflow and slows down the rendering.

### Steps to reproduce
1. Download the [Vaadin Starter](https://vaadin.com/start/pre-release) (I used the `Plain Java Servlet`)
2. Add the following code to `MainView.java`:
```Java
    private Button btn;
    private VerticalLayout form;
    private HashMap<String, String> model;
    public MainView() {
        model = new HashMap<>();
        setSizeFull();
        btn = new Button("Create Form", e -> recreateForm());
        btn.getStyle().set("cursor", "pointer");
        add(btn);
    }
    private void recreateForm() {
        if (form != null)
            remove(form);
        generateForm();
        add(form);
    }
    private void generateForm() {
        Binder<HashMap<String, String>> binder = new Binder<>();
        form = new VerticalLayout();
        VerticalLayout group = null;
        HorizontalLayout hGroup = null;
        for (int i = 0; i < 500; i ++) {
            if (group == null || i % 5 == 0)
                form.add(group = new VerticalLayout());
            if (hGroup == null || i % 2 == 0)
                group.add(hGroup = new HorizontalLayout());
            long rand = Math.round(Math.random() * 100) * (i + 1);
            String id = "tf" + i;
            TextField tf = new TextField("tf" + rand);
            binder.bind(tf, map -> map.get(id), (map, value) -> map.put(id, value));
            model.put(id, "v" + rand);
            hGroup.add(tf);
        }
        binder.readBean(model);
        binder.addValueChangeListener(e -> {
            try {
                binder.writeBean(model);
            }
            catch (ValidationException exc) {
            }
        });
    }
```

3. Open the Browser and click the `Create Form` Button.
   The rendering took about 4s in my case.
   Removing the `this._dispatchIronResizeEventIfNeeded('Height', this.offsetHeight);` from the `__observeOffsetHeight` method reduced the rendering time to about 2.5s.

### Screenshots
Chrome Performance analysis without patching the `TextFieldMixin`:
![image](https://user-images.githubusercontent.com/18258317/62767356-c5ebc580-ba94-11e9-9341-1b08d1ee403d.png)

Bottom-Up Tab of the performance analysis:
![image](https://user-images.githubusercontent.com/18258317/62767424-e7e54800-ba94-11e9-9f8b-633ab61af6b8.png)

Chrome Performance analysis after patching the `TextFieldMixin`:
![image](https://user-images.githubusercontent.com/18258317/62767473-06e3da00-ba95-11e9-8920-c65ab52b57a6.png)

### Notes
Executing `this._dispatchIronResizeEventIfNeeded('Height', this.offsetHeight);` in `beforeNextRender` achieved similar performance as removing it completely.
As I am pretty new to Polymer, I don't know if it has any side effects, but in my case the result looked the same.

### Browsers Affected
I tested it in Chrome

**Comment by hari2m** [comment]
I am using Vaadin-text-field in a grid where there are multiple columns that has an input field. I did a performance check on this in chrome and found that it is using more than 90% of time to render the page.

![image](https://user-images.githubusercontent.com/10014592/72015001-8e8d6a80-3226-11ea-8927-ffa4ef61f457.png)

Looks like the layout and rendering part needs to be fixed in this.

Is this actually built to handle such scenarios or is it built just to use inside a form? I just wanted to know if I am using it wrong.

**Comment by mvysny** [comment]
The same behaviour can be observed with ComboBox as well:

```java
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base", enableInstallPrompt = false)
@CssImport("./styles/shared-styles.css")
@CssImport(value = "./styles/vaadin-text-field-styles.css", themeFor = "vaadin-text-field")
public class MainView extends VerticalLayout {

    private Button btn;
    private VerticalLayout form;

    public MainView() {
        setSizeFull();
        btn = new Button("Create Form", e -> recreateForm());
        btn.getStyle().set("cursor", "pointer");
        add(btn);
    }

    private void recreateForm() {
        if (form != null)
            remove(form);
        generateForm();
        add(form);
    }

    private void generateForm() {
        form = new VerticalLayout();
        VerticalLayout group = null;
        HorizontalLayout hGroup = null;
        for (int i = 0; i < 500; i++) {
            if (group == null || i % 5 == 0)
                form.add(group = new VerticalLayout());
            if (hGroup == null || i % 2 == 0)
                group.add(hGroup = new HorizontalLayout());
            long rand = Math.round(Math.random() * 100) * (i + 1);
            String id = "tf" + i;
            ComboBox<String> tf = new ComboBox<>("tf" + rand);
            tf.setItems("a", "b", "c");
            hGroup.add(tf);
        }
    }
}
```

![Screenshot from 2020-08-14 14-33-00](https://user-images.githubusercontent.com/254091/90245348-2c8b8800-de3b-11ea-9e42-aa57dfba7ded.png)
