### ISSUE TITLE
vaadin-number field doesn't send click event if it's readonly

### ISSUE THREAD

**Issue by realansgar** [vaadin/vaadin-text-field#427]
### Description
`<vaadin-text-field readonly></vaadin-text-field>` sends `click` events.
`<vaadin-number-field readonly></vaadin-number-field>` doesn't send `click` events.
Which behaviour is intended? Right now it's inconsistent.

### Expected outcome
`<vaadin-number-field readonly></vaadin-number-field>` should send `click` events.

### Actual outcome
`<vaadin-number-field readonly></vaadin-number-field>` doesn't send `click` events.

### Live Demo
https://aquatic-beaufort.glitch.me/
Code: https://glitch.com/edit/#!/aquatic-beaufort

### Steps to reproduce
1. Put a `vaadin-number-field` element in the page.
2. Set it to readonly.
3. Add a `click` eventlistener to it.
4. Click.
5. Nothing happens.

### Browsers Affected
Tested only Chrome and Firefox
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by realansgar** [comment]
It seems that [this](https://github.com/vaadin/vaadin-text-field/blob/704ed9a76719ee4297ea505a9bd8065a58b3e4c1/src/vaadin-number-field.html#L14) is the culprit. The `:host([readonly]) {pointer-events: none;}` style leads to the whole text field being unclickable. The user can no longer select the value to copypaste it somewhere else. I can also no longer listen for click events to show some custom ui.
This alternative snippet only blocks click events from going through to the in-/decrease buttons while still allowing the user to select and copy the current value and the developer to add further logic.
```
:host([readonly]) [part="decrease-button"],
:host([readonly]) [part="increase-button"] {
    pointer-events: none;
}
```

**Comment by web-padawan** [comment]
Yes, it is a bug as the original commit only referenced buttons: https://github.com/vaadin/vaadin-text-field/pull/110/commits/3f132a876fca214509e4fb05b71f13495d459831

Thanks for the investigation. I will submit a PR to fix that.
