### ISSUE TITLE
duplicate registrations since 2.5.6

### ISSUE THREAD

**Issue by robrez** [vaadin/vaadin-text-field#485]
### Description
One of my projects has started receiving duplicate registration errors on vaadin-text-field since 2.5.6 was released.  I'm not quite sure what's going on w/ npm resolution, but `^2.0.0` will not select anything `>=2.6.0`...  so a couple packages (combobox, select) are creating duplicates.

Maybe this is because 2.6.1 was released last week and 2.5.6 just now?

You can see the semver calculator refuse to select 2.6.0, 2.6.1 https://semver.npmjs.com/

**Comment by web-padawan** [comment]
Thanks for reporting, I corrected the `dist-tag` manually:
```
$ npm dist-tag add @vaadin/vaadin-text-field@2.6.1 latest
+latest: @vaadin/vaadin-text-field@2.6.1
```

We will work to prevent that from happening in future.

**Comment by web-padawan** [comment]
Closing as fixed (for now) and in favor of https://github.com/vaadin/magi-cli/issues/61
