### ISSUE TITLE
Focus style not applied when clicking in textfield

### ISSUE THREAD

**Issue by Neid02** [vaadin/vaadin-text-field#492]
### Description
When i click in textfield component, the field is not marked as focused.

### Expected outcome
A focus halo must be visible when i click in a textfield.

### Actual outcome
When i click in a textfield, no focus halo is added.
But when i access the textfield using TAB key, the focus halo is added.
#### Remarks
1. The same behaviour occurs with `vaadin-combo-box` and `vaadin-text-area`
2. When using TAB, the CSS attribute **focus-ring** is added to the component but not when clicked.

### Steps to reproduce
1. Put a `vaadin-text-field` element in a page.
2. Click in the text field

### Browsers Affected
Tests done with Firefox 78.0.2 (64 bits) and Google Chrome 84.0.4147.89
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
![click](https://user-images.githubusercontent.com/21203516/88063405-4999a780-cb6a-11ea-9e27-1bc4deb0e6c9.png)
![tab](https://user-images.githubusercontent.com/21203516/88063411-4b636b00-cb6a-11ea-9726-6275f3825b60.png)

**Comment by web-padawan** [comment]
This is working as intended. There are two different attributes: `focused` and `focus-ring`, respectively.
Lumo only applies focus outline to `focus-ring` by design. This was done by 9544e5e79c26437f8d75f1d396c74ece07005028

You can apply custom CSS using `@CssImport` to make it work:

```
@CssImport(value = "./styles/my-text-field.css", themeFor = "vaadin-text-field")
```

The file should look like this:

```css
:host([focused]) [part="input-field"] {
  box-shadow: 0 0 0 2px var(--lumo-primary-color-50pct);
}
```

**Comment by Neid02** [comment]
Thanks for the reply.
I had already done it :) , but it's really weird to remove this HTML native behaviour and to have to apply a specific style to achieve this.

**Comment by sebdavid** [comment]
I don't understand that choice. If I read the commit you specified ("Updated visual look’n’feel (FFS), remove all box-shadows (excluding focus-ring)"), it was done on purpose.
I'm wondering why when using the -tab- key the focus outline would be displayed whereas it isn't when we click in the field, or vice versa. It is two different behaviours for the same field state (focused). It is not consistent (at least from my point of view).

**Comment by web-padawan** [comment]
Ping @jouni, this intention is something worth documenting in the design system documentation.
