### ISSUE TITLE
NewLine '\n' related issue

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-text-field#498]
Hi,
I have a string which is returned by a JAVA API as follows.

`var text = "Enjoy True Value Tuesday!\nExclusive Bhangra Class tomorrow at 7am.\nAlso get flat discount Rs.2500\/- on all memberships.\nFirst come First book.Limited 10 ";`

When I set the text of the `vaadin-text-area` to this string it does not show the full text.

![Screenshot from 2020-09-08 11-21-13](https://user-images.githubusercontent.com/1386911/92438142-e7ead680-f1c5-11ea-91dc-ed6abf1d2b5b.png)

I don't know what is the problem here. I have tried to change the newline to "&#13;&#10;" as suggested [here](https://jsfiddle.net/v0y3xvpx/1/) but it does not solve the problem
![Screenshot from 2020-09-08 11-32-23](https://user-images.githubusercontent.com/1386911/92438759-08fff700-f1c7-11ea-885f-2af4b545c763.png)

Can anyone please give some pointer? Is this a bug?

**Comment by sudipta1411** [comment]
Ok, this is not related to newline. The thing is that there is no way to scroll the text as the text area is readonly. To repeat that,
go to [vaadin demo page](https://vaadin.com/components/vaadin-text-area/html-examples/text-area-demos) and select any text-area using chrome-dev tools. Then in console do the following

`$0.readOnly=true;`
`$0.value=text;`
The output is as shown in the below image 
![Screenshot from 2020-09-08 14-59-49](https://user-images.githubusercontent.com/1386911/92459177-f9db7200-f1e3-11ea-9a9b-68d7b7fd7bd7.png)

You can not focus on the text area anymore, so you can not scroll the text.

**Comment by tomivirkki** [comment]
I wonder if you're setting the value to the internal `<textarea>` element here? You should select the `<vaadin-text-area>` instead and use `$0.readonly = true` and `$0.value = ...`

**Comment by tomivirkki** [comment]
Closing as inactive/not reproducible.
