### ISSUE TITLE
Required Indicator not showing when using Binder

### ISSUE THREAD

**Issue by szyuGH** [vaadin/vaadin-text-field#519]
When using Binder or BeanValidationBinder and setting a field with asRequired, the indicator is not showing.

`binder = new BeanValidationBinder<>(Person.class);
binder.forField(firstname).asRequired().bind(Person::getFirstName, Person::setFirstName);`

I also tried with setting required and requiredIndicatorVisible without success...
`firstname.setRequired(true);
firstname.setRequiredIndicatorVisible(true)`

**Comment by rolfsmeds** [comment]
Looks like you're using FormItem to render labels on the side. Unfortunately that does not support required indicator: https://github.com/vaadin/vaadin-form-layout/issues/122
