### ISSUE TITLE
Add default invalid styles

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-text-field#53]
Currently, the `invalid` state isn't visible in any way in the non-styled examples.

![screen shot 2017-04-04 at 13 50 25](https://cloud.githubusercontent.com/assets/1039468/24653264/bd3a1c34-193d-11e7-85f2-33a92edccab8.png)

**Comment by limonte** [comment]
Default styling for invalid inputs was expected by DX tests participants.

Funny part is that there IS default styling in Firefox:

![](https://i.imgur.com/sTIk8LN.png)

**Comment by jouni** [comment]
Let’s add similar default invalid style for the element as Firefox has (a red box shadow). Mention clearly in the examples what the user needs to do to override those default styles.

**Comment by jouni** [comment]
Closely related (something we should follow more closely with all our elements): https://github.com/webcomponents/gold-standard/wiki#Styling
