### ISSUE TITLE
ValueChangeListener was invoked unexpectedly

### ISSUE THREAD

**Issue by t0920008899** [vaadin/vaadin-text-field#536]
I created a TextField  with valuechangemode set to ON_CHANGE, and add a valuechangelistener which update a ComboxBox's dataprovider filter based upon the entered value. If that textfield was focused programmatically (like textfield.focus()), the listener was invoked as expected. However, I found that, if that textfield was focused by mouse clicked or tab key, the listener would be invoked everytime a key was hit. Please kindly investigate and advise where I might get wrong.

Thanks.

**Comment by web-padawan** [comment]
Closing per above comment. Please submit a new issue with a code example if the problem is still valid.
