### ISSUE TITLE
PasswordField toggle eye not working in IE11

### ISSUE THREAD

**Issue by sblommers** [vaadin/vaadin-text-field#538]
You can easily check it on https://bakery-flow.demo.vaadin.com/login using IE11
When I set this:
```
pwd.getElement().setAttribute("password-visible", true);
pwd.getElement().callFunction("_setPasswordVisible", true);
pwd.setRevealButtonVisible(true);
```
I am able to toggle it to *invisible* just 1 time, toggling back to reveal it does not seem to work in IE11

**Comment by web-padawan** [comment]
Tested with the following example and could not reproduce:

```java
PasswordField passwordField = new PasswordField();
passwordField.setLabel("Password");
passwordField.setValue("secret1");
passwordField.setRevealButtonVisible(false);

NativeButton button = new NativeButton("Toggle", event -> {
    passwordField.setRevealButtonVisible(true);
});

add(passwordField, button);
```

![ie-ok](https://user-images.githubusercontent.com/10589913/96098170-7bf14180-0eda-11eb-9f8f-4ab440ee9c88.gif)

Closing as fixed. Please submit a new issue with a code example to reproduce it if the problem persists.
