### ISSUE TITLE
Error indicator lost when focusing and defocusing invalid required field

### ISSUE THREAD

**Issue by macprzepiora** [vaadin/vaadin-text-field#539]
To reproduce:

1. Create a text field that is required and has validation (see https://gist.github.com/macprzepiora/665597644c9e7b39c2746872a579f149 for a complete example showing the issue)
2. Run the app
3. Enter invalid value into the text field
4. Defocus the field
5. Focus again
6. Defocus the field again

Observed result: Error indicator disappears

Expected result: Error indicator is still shown

**Comment by tomivirkki** [comment]
Closing. Seems to work on V14.4
