### ISSUE TITLE
Text field doesn't hide the error message when it becomes valid

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-text-field#543]
See the code below.

```
Binder<String> binder = new Binder<>();
        TextField field = new TextField();
        field.setValue("foo");
        binder.forField(field)
                .withValidator(text -> !text.equals("no"), "Error message")
                .bind(item -> item, (item, value) -> {
                });
        add(field);
```

Steps to reproduce:
- Remove the current text field value and type `"no"` ( which is invalid value).
- Check that text field became invalid and shows the error message.
- Make the text field valid again.

Expected: no error message is shown (the field by the way became valid since there is no `invalid` attribute).
Reality: the error message is shown.

It happens because binder doesn't clear the error message when the `HasValidation` component component becomes valid.
This is consequence of https://github.com/vaadin/flow/issues/3439.
There has been a discussion about this and it has been agreed that this behavior is correct.
But apparently it's not.
As I understand the bug is in the `vaadin-text-field` component since the behavior has been guaranteed on the elements side.
So this ticket is just to be able to track this on Flow side. Should be fixed on the `vaadin-text-field` side.

**Comment by web-padawan** [comment]
Closing in favor of #200 as both issues are now in the same repository. The unstyled components still behave the same.
