### ISSUE TITLE
Using instance of Text for prefix/suffix throws an exception

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field#544]
Since `com.vaadin.ui.Text` extends `Component` and `TextField.addToPrefix`/`addToSuffix` accepts `Component`s, one is tempted to do this:

```java
TextField myField = new TextField();
myField.addToPrefix(new Text("I'm prefix!"));
```

But this fails, since it tries to set attribute `slot` on a text-block, which is not a proper element.

It may be safer to not have `Text` extend `Component` and create a `HasText` interface with a default method to add text nodes to components which support it.

**Comment by web-padawan** [comment]
Closing in favor of #512
