### ISSUE TITLE
Incorrect EMail field validation 

### ISSUE THREAD

**Issue by zimmermq** [vaadin/vaadin-text-field#566]
### Description
The validation of the EMail field doesn't work proper.

### Live Demo
https://vaadin.com/components/vaadin-email-field/java-examples/email-field

### Steps to Reproduce

1. Type correct email to the field
2. Click outside the field, validation result is ok
3. Remove some parts of the email in the field so the input is an incorrect email
4. Click outside the field, validation result is still ok

### Expected Results
Validation result shouldn't be ok

### Actual Results
Validation result is ok

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] iOS Safari
- [ ] Android Chrome

Only tested with Firefox 78.6.1esr (32-Bit)

### Version

- vaadin-text-field: v2.8.2

**Comment by tomivirkki** [comment]
Hi @zimmermq 

Using Firefox, I followed the "Steps to Reproduce" with the linked example but didn't see any issues

![Kapture 2021-01-23 at 16 12 34](https://user-images.githubusercontent.com/1222264/105580583-dd586480-5d95-11eb-9c4a-1fbcbe7587c1.gif)

Can you provide a more detailed description for reproducing

**Comment by zimmermq** [comment]
Hi @tomivirkki ,

your right, I'm wrong. My steps aren't correct.

It seems that the regexp "EMAIL_PATTERN" at "EmailField.class" isn't correct.
"^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$"

Therefore, addresses without a dot are also considered correct, e.g.: "test@examplecom".

The "EmailValidator" uses
"^([a-zA-Z0-9_\\.\\-+])+@(([a-zA-Z0-9-])+\\.)+([a-zA-Z0-9]{2,4})+$"

My best guess:
"^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@(([a-zA-Z0-9-])+\\.)+([a-zA-Z0-9]{2,4})+$"

[Wiki Email](https://en.wikipedia.org/wiki/Email_address)

Kind regards

**Comment by tomivirkki** [comment]
Seems that version of EmailField running at https://vaadin.com/components/vaadin-email-field/java-examples/email-field indeed does support dotless domain names.

This has been fixed in https://github.com/vaadin/vaadin-flow-components/pull/442 and the new version, deployed at https://vaadin.com/docs-beta/latest/ds/components/email-field/ considers dotless domains invalid.
