### ISSUE TITLE
Information about `prefix` and `suffix` usage is missing in docs page.

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-text-field#76]
There are examples on the demos page, but nothing useful on the docs page.

(This is the DX tests finding)

**Comment by jouni** [comment]
Does the “docs page” refer to the API documentation, or vaadin.com/docs?

**Comment by jouni** [comment]
If it refers to vaadin.com/docs, then this issue can be closed, as we are no longer maintaining those separate documentation pages for our elements, and the demos/examples double as the documentation.
