### ISSUE TITLE
Remove autofocus demo

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-text-field#83]
Currently, after opening the page, the autofocus example makes it scroll away from the top. This obscures first few examples on the page.

(This is the DX tests finding)

**Comment by limonte** [comment]
I tried to reproduce that issue but without success because of my big screen. Nice catch!

**Comment by limonte** [comment]
Should we add the `autofocus` to the very first demo example?

**Comment by platosha** [comment]
Not worth the demo at all IMO. It’s enough that we list it in the API doc. Usage and the result are as intuitive as it could be.
