### ISSUE TITLE
Built-in “clear” button

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#92]
As an opt-in feature (or opt-out, can be discussed), provide a built-in suffix element which, when clicked/tapped, sets the value of the field to an empty string.

The element should be an “X” icon and be shown before any other suffix elements (closest to the value).

Question: When the field is marked as required, should the clear button always be hidden?

**Comment by jouni** [comment]
Question: should <kbd>Esc</kbd> activate the clear button?

In some cases, this would probably be helpful (a search field), but in some other cases, it could be more unwanted (an email field).

I suppose this could also be an opt-in helper feature on top of the clear button itself.

**Comment by jouni** [comment]
Since this feature would be used by combo box, date picker and dropdown menu, it should be possible to opt-in/out this feature from those wrapping elements as well, even per-instance level.

**Comment by heruan** [comment]
> When the field is marked as required, should the clear button always be hidden?

I'd say no: the clear could be useful also on required fields, e.g. just to clear the value and start over.

> should <kbd>Esc</kbd> activate the clear button?

I'd say yes, if the clear button is visible; otherwise, no. This is the same behavior of the HTML5 `<input type="search">` on most browsers: a clear button is showed and <kbd>Esc</kbd> triggers it; if `type="text"` no clear button is present and <kbd>Esc</kbd> does not clear the value.

**Comment by jouni** [comment]
Adding a `clear()` method could happen at the same time with this so that there’s a convenient way to do the same thing from the API.

**Comment by tomivirkki** [comment]
Should this rather be a new text field extension, say `<vaadin-search-field>`, instead of an additional feature to the `<vaadin-text-field>`

**Comment by web-padawan** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/Events/search

**Comment by jouni** [comment]
I’m struggling to see how this feature relates to search.

The native `<input type="search">` does have a built-in clear button, but that doesn’t mean it’s the only use case that benefits from having one.

**Comment by web-padawan** [comment]
One of the advantages of the text-field opt-in feature would be using in vaadin-grid-filter.

**Comment by tomivirkki** [comment]
Starting to implement this in the next sprint as an opt-in feature. The planned API looks somewhat like: `<vaadin-text-field clear-button-visible>`

- Flag working name: `clearButtonVisible`(to align with password field's revealButtonHidden)
- Don't dispatch "change" on click
- Same theming API and appearance as that of `<vaadin-combo-box>`
- Use the suffix area of the components (place as the first suffix)

Work on any open design questions ad-hoc with the designers. The remaining design/API issues we'll tackle during UX/DX phase.
