### ISSUE TITLE
Set a default height for part=input-field

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-text-field#99]
Adding/removing icons to prefix/suffix slots makes the element layout change.

That is an issue when adding mobile friendly clear/toggle buttons in other elements like vaadin-combo-box. Otherwise setting a height in other elements needs to define a theme block and repeat all theme-default properties.

Here a screenshot with the problem and possible solution

http://g.recordit.co/nDrZJnpxqv.gif

**Comment by jouni** [comment]
Discussed with @tomivirkki, and we concluded that we should leave the button sizes to browser defaults (1em basically), and let proper themes handle touch target sizes and making the buttons/icons pretty. So let’s not fix the input height in the default styles.

It’s sometimes difficult to decide when we are doing developers a favor and when we are stepping on their toes and trying to help too much. This is one of those cases, and I think we can now make the decision to do less, and reconsider this in the future if needed.
